version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - echo Deploying static assets to s3://brothersofvincent at `date`
      - aws s3 sync ./src/ s3://brothersofvincent.com --cache-control max-age=0